# Generated by Django 5.0.7 on 2024-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employeeattendance_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('I', 'IN'), ('O', 'OUT')], max_length=1),
        ),
    ]
